### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by droidslying** [xnti/discord-nitro-generator#3]
Error: Cannot find module '/home/runner/discordnitrobot/util/logger'
Require stack:
- /home/runner/discordnitrobot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at /home/runner/discordnitrobot/index.js:17:16
    at Script.runInContext (vm.js:130:18)
    at Object.<anonymous> (/run_dir/interp.js:209:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)

**Comment by xnti** [comment]
It is because of logger.js module cannot be found. If you have `logger.js` in util directory it will not happen I guess
